import * as THREE from "three";

const WINDOW_WIDTH = window.innerWidth;
const WINDOW_HEIGHT = window.innerHeight;

const CAMERA_FOV = 50;
const MIN_CAMERA_RADIUS = 3;
const MAX_CAMERA_RADIUS = 15;
const ROTATION_SENSITIVITY = 0.5;
const ZOOM_SENSITIVITY = 0.02;
const PAN_SENSITIVITY = -0.01;
const MIN_CAMERA_ELEVATION = 30;
const MAX_CAMERA_ELEVATION = 90;
const DEGREE_TO_RADIUS = Math.PI / 180;

const Y_AXIS = new THREE.Vector3(0, 1, 0);

const LEFT_MOUSE_BUTTON = 0;
const MIDDLE_MOUSE_BUTTON = 1;
const RIGHT_MOUSE_BUTTON = 2;

const COLORS = {
  SKY: 0x87ceeb,
  GRASS: 0x4caf50,
};

export {
  WINDOW_WIDTH,
  WINDOW_HEIGHT,
  CAMERA_FOV,
  LEFT_MOUSE_BUTTON,
  MIDDLE_MOUSE_BUTTON,
  RIGHT_MOUSE_BUTTON,
  MIN_CAMERA_RADIUS,
  MAX_CAMERA_RADIUS,
  ROTATION_SENSITIVITY,
  ZOOM_SENSITIVITY,
  PAN_SENSITIVITY,
  MIN_CAMERA_ELEVATION,
  MAX_CAMERA_ELEVATION,
  DEGREE_TO_RADIUS,
  Y_AXIS,
  COLORS,
};
